### ISSUE TITLE
在openwrt上启动tailscale脚本报如下错误，tailscald进程无法启动！

### ISSUE THREAD

**Issue by fu7100** [CH3NGYZ/tailscale-openwrt#12]
failed to connect to local tailscaled; it doesn't appear to be running

**Comment by CH3NGYZ** [comment]
使用chinese_mainland分支的脚本，安装完毕之后，手动执行 `tailscale_downloader` 看看能否正常下载安装

**Comment by CH3NGYZ** [comment]
由于长时间未跟进进度, 本issue已被关闭
