### ISSUE TITLE
exit node无法正常使用【急需修复】

### ISSUE THREAD

**Issue by 24kbrother** [CH3NGYZ/tailscale-openwrt#15]
上周更新了/bin/tailscale_download文件，
导致/etc/resolv.conf文件被增加了新的nameserver 100.100.100.100, 这条会导致节点如果使用openwrt作为出口节点，无法正常上网，因为DNS被修改为100.100.100.100公网不可达。
需要UP修复一下。

**Comment by CH3NGYZ** [comment]
> 上周更新了/bin/tailscale_download文件， 导致/etc/resolv.conf文件被增加了新的nameserver 100.100.100.100, 这条会导致节点如果使用openwrt作为出口节点，无法正常上网，因为DNS被修改为100.100.100.100公网不可达。 需要UP修复一下。

上周因为有另一位和我说这里得添加上100.100.100.100，因为我也不使用exit nodes，所以添加了没啥毛病，就更新了代码，那我现在先暂时删除掉吧，你在过个半小时，更新一下脚本测试，但我也比较奇怪的是, /etc/resolv.conf中哪怕第一个地址100.100.100.100不可访问，系统也会尝试使用后续的223.5.5.5和119.29.29.29，应该会按照文件中列出的 nameserver 顺序来进行 DNS 查询，直到找到一个可以响应的 DNS 服务器

**Comment by 24kbrother** [comment]
你删除掉肯定是可以的，手动删除/usr/bin/tailscale_downloader里面的这行是没问题的，
