### ISSUE TITLE
希望本项目增加nftables支持

### ISSUE THREAD

**Issue by TKTick** [CH3NGYZ/tailscale-openwrt#17]
### 问题描述
openwrt 在 22.03 以上版本将防火墙架构从 iptables 切换到 nftables 。
tailscale官方在[1.48.0版本](https://tailscale.com/changelog#2023-08-16)支持了 nftables ，但默认还是 iptables 模式，在 22.03 以上版本且没有安装 iptables-nft 的路由会无法启动并报错：`failed to connect to local tailscaled; it doesn't appear to be running openwrt`
虽然可以通过安装 iptables-nft 来转换，但是在openwrt防火墙界面会提示新旧语法可能导致流量漏放，并且openwrt官方已经切换为nftables，该办法始终不是最优解。
### 解决办法
根据[官方文档](https://tailscale.com/kb/1294/firewall-mode#firewall-mode-heuristic)添加环境变量`TS_DEBUG_FIREWALL_MODE`，具体用法如下：
| Value | Description |
|--------|--------|
| `auto` | A [heuristic](https://tailscale.com/kb/1294/firewall-mode#heuristic) is used to decide between iptables and nftables. |
| `iptables` | `iptables` is used. |
| `nftables` | `nftables` is used. |
| No value set | The default of iptables is used. | 

如何在本项目中的添加nftables支持

- 在`/etc/init.d/tailscale`中添加环境变量，即在`procd_close_instance`前添加`procd_set_param env TS_DEBUG_FIREWALL_MODE=auto`

- 或者使用uci
 `sed -i '/  procd_close_instance/i\procd_set_param env TS_DEBUG_FIREWALL_MODE=auto' /etc/init.d/tailscale`

但在我的路由immortalwrt 23.05.3中设置为`auto`并不能正常启动，需要设置成`nftables`才能正常启动。我暂时不能判断是属于immortalwrt的问题还是tailscale的问题。如果作者要支持该特性或许需要增加代码判断或者在readme里增加相关提示。
![图片](https://github.com/user-attachments/assets/e12364c1-2725-421f-bcf0-013cbc060889)

**Comment by CH3NGYZ** [comment]
代码已新增 `procd_set_param env TS_DEBUG_FIREWALL_MODE=auto` , 感谢您的建议, 目前先以`auto`模式, 启动不了再手动切换
