### ISSUE TITLE
下载失败，梯子已经开了

### ISSUE THREAD

**Issue by rotent** [CH3NGYZ/tailscale-openwrt#19]
![1725969905627](https://github.com/user-attachments/assets/6e2d1c83-9566-449b-b0ab-4bd0bff32a18)
![1725969645927](https://github.com/user-attachments/assets/365d4d99-f75d-4e74-a26d-f02b7bbfe7c9)

**Comment by CH3NGYZ** [comment]
检查DNS

**Comment by CH3NGYZ** [comment]
此问题非脚本问题, 是你路由器自身网络问题, 在路由器内 `nslookup ghproxy.cc` 检查一下

**Comment by rotent** [comment]
因为我学校是校园网，禁止了公共dns
![image](https://github.com/user-attachments/assets/b2ca3576-50d0-4a27-b305-a9f8687e0977)

**Comment by rotent** [comment]
主要是前面的流程都没问题，到了下载tailscale本体的时候就不行了
![image](https://github.com/user-attachments/assets/e6ccd679-cf5a-4b97-98a7-4bfc4b9f163f)

**Comment by CH3NGYZ** [comment]
试试路由器内 用curl或wget下载这个文件 , 看看多长时间下载完, 脚本内置10秒, 10秒内下不完就视为失败.
`wget -O /dev/null https://ghproxy.cc/https://github.com/CH3NGYZ/tailscale-openwrt/releases/download/1.72.1/tailscale_1.72.1_arm64.tgz
`

`curl -o /dev/null https://ghproxy.cc/https://github.com/CH3NGYZ/tailscale-openwrt/releases/download/1.72.1/tailscale_1.72.1_arm64.tgz
`

**Comment by CH3NGYZ** [comment]
我已经修改超时为30秒, 请再试一次

**Comment by rotent** [comment]
成功了！感谢！！
