### ISSUE TITLE
修改了下tailscale_downloader脚本，增加备份程序功能，实现当程序更新失败时能从原来备份的程序里启动

### ISSUE THREAD

**Issue by sheep-sleep** [CH3NGYZ/tailscale-openwrt#20]
[tailscale_downloader.txt](https://github.com/user-attachments/files/17161295/tailscale_downloader.txt)

**Comment by CH3NGYZ** [comment]
谢谢你的贡献, 但是由于本项目旨在为 `空间不足但内存充足` 的用户提供一种可以直接在内存中运行 Tailscale 的解决方案，如果将 Tailscale 备份到存储中，会冲突于本项目的目的。

你修改的这个脚本实际上更适合用于 `存储充足、内存充足且希望快速更新最新版Tailscale同时又怕更新失败` 的用户。这些用户可能已经拥有足够的存储空间，可以轻松地将 Tailscale 备份到存储中，然后使用本项目提供的脚本来在启动时更新 Tailscale。

要不我重构下这个项目, 给定两个选项
1.传统装入内存中
2.空间充足直接固化到存储中
你觉得怎么样?

**Comment by sheep-sleep** [comment]
感谢大佬回复，您描述的很准确，我用的场景是软路由，内存和储存都很充足。我觉得两个选项都可以。

**Comment by CH3NGYZ** [comment]
那我收假后优化一下脚本，如果空间充足则会提供备份启动功能，存储不足则照旧
