### ISSUE TITLE
下载安装脚本失败，尝试下一个代理

### ISSUE THREAD

**Issue by shenyb47** [CH3NGYZ/tailscale-openwrt#24]
INSTALL: 包 coreutils-timeout 未安装，开始安装...
Unknown package 'coreutils-timeout'.
Collected errors:
 * opkg_install_cmd: Cannot install package coreutils-timeout.
INSTALL: 安装 coreutils-timeout 失败，跳过该包，如果无法正常运行 tailscale，请排查是否需要手动安装该包
sh: timeout: not found
INSTALL: ------------------
下载安装脚本失败，尝试下一个代理
---------------------------
sh: timeout: not found
INSTALL: ------------------
下载安装脚本失败，尝试下一个代理
---------------------------
sh: timeout: not found
INSTALL: ------------------
下载安装脚本失败，尝试下一个代理
---------------------------
sh: timeout: not found
INSTALL: ------------------
下载安装脚本失败，尝试下一个代理
---------------------------
sh: timeout: not found
INSTALL: ------------------
下载安装脚本失败，尝试下一个代理
---------------------------
sh: timeout: not found
INSTALL: ------------------
下载安装脚本失败，尝试下一个代理
---------------------------
INSTALL: -------------------------
所有代理下载均失败，请检查网络、DNS或稍后再试

**Comment by CH3NGYZ** [comment]
错误都提示给你了, 手动装下 coreutils-timeout
