### ISSUE TITLE
想请问一下upnp相关

### ISSUE THREAD

**Issue by RyensX** [CH3NGYZ/tailscale-openwrt#26]
发现只要开启tailscale就会导致upnp无法起作用，有什么解决办法吗？

**Comment by CH3NGYZ** [comment]
抱歉, 我装tailscale的openwrt是作为旁路由来用的, 所以没有过多关注upnp, 帮不到你 :(

**Comment by RyensX** [comment]
> 抱歉, 我装tailscale的openwrt是作为旁路由来用的, 所以没有过多关注upnp, 帮不到你 :(

好的，我再自己排查一下，感谢开发。
