### ISSUE TITLE
Does the script support your machine architecture? 脚本是否支持您的机器架构?

### ISSUE THREAD

**Issue by CH3NGYZ** [CH3NGYZ/tailscale-openwrt#6]
Leave a comment contains output from the script about the machine architecture and whether it was installed and running successfully.
留下评论，包含脚本关于机器架构的输出, 以及Tailscale是否安装成功、运行成功。

例:
x86_64|amd64  安装成功 运行成功
armv7l|arm 安装成功 运行成功

**Comment by hotwa** [comment]
mipsle|mips installed successfully and running successfully.

the tailscaled save in /tmp.

**Comment by monkeyotg** [comment]
x86_64|amd64 installed successfully and running successfully
mips | arch also works ok

**Comment by CH3NGYZ** [comment]
> x86_64|amd64 installed successfully and running successfully

收到, 感谢您的回复

**Comment by AKAEL0817** [comment]
arch_:aarch64| arch:arm64 安装成功，运行成功

**Comment by wangweitung** [comment]
INSTALL: ---------------------------------------------
当前机器的架构是 arch_:x86_64| arch:amd64

**Comment by AKAEL0817** [comment]
支持

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: wangweitung ***@***.***>
发送时间: Wednesday, March 27, 2024 10:56:55 PM
收件人: CH3NGYZ/tailscale-openwrt ***@***.***>
抄送: AKA-88EL ***@***.***>; Comment ***@***.***>
主题: Re: [CH3NGYZ/tailscale-openwrt] Does the script support your machine architecture? 脚本是否支持您的机器架构? (Issue #6)


INSTALL: ---------------------------------------------
当前机器的架构是 arch_:x86_64| arch:amd64

―

**Comment by cero-ss** [comment]
ARMv8|arm 安装成功 运行成功

**Comment by x6nux** [comment]
i686 安装失败

**Comment by CH3NGYZ** [comment]
> i686 安装失败

请附上详细安装日志, 我也不知道i686对应的文件名叫什么

**Comment by anytalks** [comment]
当前机器的架构是 [x86_64]
脚本内置的架构代码可能有误,不符合您的机器

。。。。。。

**Comment by CH3NGYZ** [comment]
closed, 项目趋于稳定, 可以不用再提交了
