### ISSUE TITLE
一直获取不到版本号，是代理的问题么

### ISSUE THREAD

**Issue by iMaxxxxxxx** [CH3NGYZ/tailscale-openwrt#9]
![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/362481e1-5bab-4dfd-948e-53d61fe06d9e)

**Comment by iMaxxxxxxx** [comment]
![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/a92fa7e5-ffc1-4464-acde-c783a982f5ab)

**Comment by CH3NGYZ** [comment]
为啥看不见安装日志呢，奇怪
你是不是用的passwall，clash等翻墙工具

**Comment by CH3NGYZ** [comment]
> ![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/a92fa7e5-ffc1-4464-acde-c783a982f5ab)
> 

为啥看不见安装日志呢，好奇怪

**Comment by iMaxxxxxxx** [comment]
昨天还运行了一次代理安装，有安装日志，然后最后一步启动前台程序的时候卡住了
我之前装的是一个1.26还是多少版本的，也是通过你的脚本安装的
是有PassWall和ShadowSocksR Plus+这两个是启用状态
![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/38f536f3-76e6-4eac-87d5-6cf812d8db89)

**Comment by CH3NGYZ** [comment]
> 昨天还运行了一次代理安装，有安装日志，然后最后一步启动前台程序的时候卡住了
> 我之前装的是一个1.26还是多少版本的，也是通过你的脚本安装的
> 是有PassWall和ShadowSocksR Plus+这两个是启用状态
> ![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/38f536f3-76e6-4eac-87d5-6cf812d8db89)
> 
> 

我觉得可能是代理的问题，关掉代理，卸载重启后重新安装

**Comment by iMaxxxxxxx** [comment]
好的，我试试。
我运行了rm -rf /tmp/tailscale是不是旧版本一起删掉了，昨天执行卸载命令，也是没有日志

**Comment by iMaxxxxxxx** [comment]
![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/43846328-af73-4d32-a9b5-f84c9469a079)

**Comment by CH3NGYZ** [comment]
> 好的，我试试。
> 我运行了rm -rf /tmp/tailscale是不是旧版本一起删掉了，昨天执行卸载命令，也是没有日志
> 

那你把安装脚本下下来之后，手动给予执行权限，然后用sh 脚本.sh执行看看什么日志

**Comment by iMaxxxxxxx** [comment]
关掉代理重启后运行的
![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/f51d0397-3ea3-4fe9-a1e1-4c5da90a347f)

**Comment by CH3NGYZ** [comment]
> 关掉代理重启后运行的
> ![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/f51d0397-3ea3-4fe9-a1e1-4c5da90a347f)
> 

你把后面的 竖杠 sh删掉，只留wget链接，删掉选项里的q，只留下大写O，然后看下载脚本的日志

**Comment by iMaxxxxxxx** [comment]
![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/f79157e9-0598-4d19-b613-49abbc348d92)

**Comment by CH3NGYZ** [comment]
> ![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/f79157e9-0598-4d19-b613-49abbc348d92)
> 

那就是脚本下不下来咯，试试curl www.baidu.com什么效果，如果还连不通，那你网络环境有问题，如果能联通，那就是ghproxy不好使

**Comment by CH3NGYZ** [comment]
> ![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/f79157e9-0598-4d19-b613-49abbc348d92)
> 

感觉你的dna有问题，检查下吧

**Comment by iMaxxxxxxx** [comment]
确实是我路由表有问题，添加之后可以正常卸载并重新安装新版本了，谢谢大佬

**Comment by CH3NGYZ** [comment]
> 确实是我路由表有问题，添加之后可以正常卸载并重新安装新版本了，谢谢大佬
> 

ok的没问题，issue关掉了

**Comment by iMaxxxxxxx** [comment]
最后有个报错
![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/56b56ef3-1bdb-4263-9bba-da17713f85a9)

**Comment by CH3NGYZ** [comment]
> 最后有个报错
> ![image](https://github.com/CH3NGYZ/tailscale-openwrt/assets/141819436/56b56ef3-1bdb-4263-9bba-da17713f85a9)
> 

你是不是同一个账号下其他设备开了路由模式？那这样是正常的

**Comment by iMaxxxxxxx** [comment]
感谢感谢
